language: go
services:
  - docker
# Needed for e2e tests
sudo: true
go: 1.x
go_import_path: github.com/avagin/csi-vstorage
install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure -vendor-only
  - make vstorage
script:
  - go fmt $(go list ./... | grep -v vendor) | wc -l | grep 0
  - go vet $(go list ./... | grep -v vendor)
